import { PianoKey } from "../types/pianoKey.ts";

export const pianoKeys: PianoKey[] = [
	{
		note: "A0",
		localizedNote: "A0",
		vexFlowNote: "a/0",
		frequency: 27.5,
		isBlack: false,
		octave: 0,
	},
	{
		note: "A#0",
		localizedNote: "A#0",
		vexFlowNote: "a#/0",
		frequency: 29.14,
		isBlack: true,
		octave: 0,
	},
	{
		note: "B0",
		localizedNote: "B0",
		vexFlowNote: "b/0",
		frequency: 30.87,
		isBlack: false,
		octave: 0,
	},
	{
		note: "C1",
		localizedNote: "C1",
		vexFlowNote: "c/1",
		frequency: 32.7,
		isBlack: false,
		octave: 1,
	},
	{
		note: "C#1",
		localizedNote: "C#1",
		vexFlowNote: "c#/1",
		frequency: 34.65,
		isBlack: true,
		octave: 1,
	},
	{
		note: "D1",
		localizedNote: "D1",
		vexFlowNote: "d/1",
		frequency: 36.71,
		isBlack: false,
		octave: 1,
	},
	{
		note: "D#1",
		localizedNote: "D#1",
		vexFlowNote: "d#/1",
		frequency: 38.89,
		isBlack: true,
		octave: 1,
	},
	{
		note: "E1",
		localizedNote: "E1",
		vexFlowNote: "e/1",
		frequency: 41.2,
		isBlack: false,
		octave: 1,
	},
	{
		note: "F1",
		localizedNote: "F1",
		vexFlowNote: "f/1",
		frequency: 43.65,
		isBlack: false,
		octave: 1,
	},
	{
		note: "F#1",
		localizedNote: "F#1",
		vexFlowNote: "f#/1",
		frequency: 46.25,
		isBlack: true,
		octave: 1,
	},
	{
		note: "G1",
		localizedNote: "G1",
		vexFlowNote: "g/1",
		frequency: 49.0,
		isBlack: false,
		octave: 1,
	},
	{
		note: "G#1",
		localizedNote: "G#1",
		vexFlowNote: "g#/1",
		frequency: 51.91,
		isBlack: true,
		octave: 1,
	},
	{
		note: "A1",
		localizedNote: "A1",
		vexFlowNote: "a/1",
		frequency: 55.0,
		isBlack: false,
		octave: 1,
	},
	{
		note: "A#1",
		localizedNote: "A#1",
		vexFlowNote: "a#/1",
		frequency: 58.27,
		isBlack: true,
		octave: 1,
	},
	{
		note: "B1",
		localizedNote: "B1",
		vexFlowNote: "b/1",
		frequency: 61.74,
		isBlack: false,
		octave: 1,
	},
	{
		note: "C2",
		localizedNote: "C2",
		vexFlowNote: "c/2",
		frequency: 65.41,
		isBlack: false,
		octave: 2,
	},
	{
		note: "C#2",
		localizedNote: "C#2",
		vexFlowNote: "c#/2",
		frequency: 69.3,
		isBlack: true,
		octave: 2,
	},
	{
		note: "D2",
		localizedNote: "D2",
		vexFlowNote: "d/2",
		frequency: 73.42,
		isBlack: false,
		octave: 2,
	},
	{
		note: "D#2",
		localizedNote: "D#2",
		vexFlowNote: "d#/2",
		frequency: 77.78,
		isBlack: true,
		octave: 2,
	},
	{
		note: "E2",
		localizedNote: "E2",
		vexFlowNote: "e/2",
		frequency: 82.41,
		isBlack: false,
		octave: 2,
	},
	{
		note: "F2",
		localizedNote: "F2",
		vexFlowNote: "f/2",
		frequency: 87.31,
		isBlack: false,
		octave: 2,
	},
	{
		note: "F#2",
		localizedNote: "F#2",
		vexFlowNote: "f#/2",
		frequency: 92.5,
		isBlack: true,
		octave: 2,
	},
	{
		note: "G2",
		localizedNote: "G2",
		vexFlowNote: "g/2",
		frequency: 98.0,
		isBlack: false,
		octave: 2,
	},
	{
		note: "G#2",
		localizedNote: "G#2",
		vexFlowNote: "g#/2",
		frequency: 103.83,
		isBlack: true,
		octave: 2,
	},
	{
		note: "A2",
		localizedNote: "A2",
		vexFlowNote: "a/2",
		frequency: 110.0,
		isBlack: false,
		octave: 2,
	},
	{
		note: "A#2",
		localizedNote: "A#2",
		vexFlowNote: "a#/2",
		frequency: 116.54,
		isBlack: true,
		octave: 2,
	},
	{
		note: "B2",
		localizedNote: "B2",
		vexFlowNote: "b/2",
		frequency: 123.47,
		isBlack: false,
		octave: 2,
	},
	{
		note: "C3",
		localizedNote: "C3",
		vexFlowNote: "c/3",
		frequency: 130.81,
		isBlack: false,
		octave: 3,
	},
	{
		note: "C#3",
		localizedNote: "C#3",
		vexFlowNote: "c#/3",
		frequency: 138.59,
		isBlack: true,
		octave: 3,
	},
	{
		note: "D3",
		localizedNote: "D3",
		vexFlowNote: "d/3",
		frequency: 146.83,
		isBlack: false,
		octave: 3,
	},
	{
		note: "D#3",
		localizedNote: "D#3",
		vexFlowNote: "d#/3",
		frequency: 155.56,
		isBlack: true,
		octave: 3,
	},
	{
		note: "E3",
		localizedNote: "E3",
		vexFlowNote: "e/3",
		frequency: 164.81,
		isBlack: false,
		octave: 3,
	},
	{
		note: "F3",
		localizedNote: "F3",
		vexFlowNote: "f/3",
		frequency: 174.61,
		isBlack: false,
		octave: 3,
	},
	{
		note: "F#3",
		localizedNote: "F#3",
		vexFlowNote: "f#/3",
		frequency: 185.0,
		isBlack: true,
		octave: 3,
	},
	{
		note: "G3",
		localizedNote: "G3",
		vexFlowNote: "g/3",
		frequency: 196.0,
		isBlack: false,
		octave: 3,
	},
	{
		note: "G#3",
		localizedNote: "G#3",
		vexFlowNote: "g#/3",
		frequency: 207.65,
		isBlack: true,
		octave: 3,
	},
	{
		note: "A3",
		localizedNote: "A3",
		vexFlowNote: "a/3",
		frequency: 220.0,
		isBlack: false,
		octave: 3,
	},
	{
		note: "A#3",
		localizedNote: "A#3",
		vexFlowNote: "a#/3",
		frequency: 233.08,
		isBlack: true,
		octave: 3,
	},
	{
		note: "B3",
		localizedNote: "B3",
		vexFlowNote: "b/3",
		frequency: 246.94,
		isBlack: false,
		octave: 3,
	},
	{
		note: "C4",
		localizedNote: "C4",
		vexFlowNote: "c/4",
		frequency: 261.63,
		isBlack: false,
		octave: 4,
	},
	{
		note: "C#4",
		localizedNote: "C#4",
		vexFlowNote: "c#/4",
		frequency: 277.18,
		isBlack: true,
		octave: 4,
	},
	{
		note: "D4",
		localizedNote: "D4",
		vexFlowNote: "d/4",
		frequency: 293.66,
		isBlack: false,
		octave: 4,
	},
	{
		note: "D#4",
		localizedNote: "D#4",
		vexFlowNote: "d#/4",
		frequency: 311.13,
		isBlack: true,
		octave: 4,
	},
	{
		note: "E4",
		localizedNote: "E4",
		vexFlowNote: "e/4",
		frequency: 329.63,
		isBlack: false,
		octave: 4,
	},
	{
		note: "F4",
		localizedNote: "F4",
		vexFlowNote: "f/4",
		frequency: 349.23,
		isBlack: false,
		octave: 4,
	},
	{
		note: "F#4",
		localizedNote: "F#4",
		vexFlowNote: "f#/4",
		frequency: 369.99,
		isBlack: true,
		octave: 4,
	},
	{
		note: "G4",
		localizedNote: "G4",
		vexFlowNote: "g/4",
		frequency: 392.0,
		isBlack: false,
		octave: 4,
	},
	{
		note: "G#4",
		localizedNote: "G#4",
		vexFlowNote: "g#/4",
		frequency: 415.3,
		isBlack: true,
		octave: 4,
	},
	{
		note: "A4",
		localizedNote: "A4",
		vexFlowNote: "a/4",
		frequency: 440.0,
		isBlack: false,
		octave: 4,
	},
	{
		note: "A#4",
		localizedNote: "A#4",
		vexFlowNote: "a#/4",
		frequency: 466.16,
		isBlack: true,
		octave: 4,
	},
	{
		note: "B4",
		localizedNote: "B4",
		vexFlowNote: "b/4",
		frequency: 493.88,
		isBlack: false,
		octave: 4,
	},
	{
		note: "C5",
		localizedNote: "C5",
		vexFlowNote: "c/5",
		frequency: 523.25,
		isBlack: false,
		octave: 5,
	},
	{
		note: "C#5",
		localizedNote: "C#5",
		vexFlowNote: "c#/5",
		frequency: 554.37,
		isBlack: true,
		octave: 5,
	},
	{
		note: "D5",
		localizedNote: "D5",
		vexFlowNote: "d/5",
		frequency: 587.33,
		isBlack: false,
		octave: 5,
	},
	{
		note: "D#5",
		localizedNote: "D#5",
		vexFlowNote: "d#/5",
		frequency: 622.25,
		isBlack: true,
		octave: 5,
	},
	{
		note: "E5",
		localizedNote: "E5",
		vexFlowNote: "e/5",
		frequency: 659.26,
		isBlack: false,
		octave: 5,
	},
	{
		note: "F5",
		localizedNote: "F5",
		vexFlowNote: "f/5",
		frequency: 698.46,
		isBlack: false,
		octave: 5,
	},
	{
		note: "F#5",
		localizedNote: "F#5",
		vexFlowNote: "f#/5",
		frequency: 739.99,
		isBlack: true,
		octave: 5,
	},
	{
		note: "G5",
		localizedNote: "G5",
		vexFlowNote: "g/5",
		frequency: 783.99,
		isBlack: false,
		octave: 5,
	},
	{
		note: "G#5",
		localizedNote: "G#5",
		vexFlowNote: "g#/5",
		frequency: 830.61,
		isBlack: true,
		octave: 5,
	},
	{
		note: "A5",
		localizedNote: "A5",
		vexFlowNote: "a/5",
		frequency: 880.0,
		isBlack: false,
		octave: 5,
	},
	{
		note: "A#5",
		localizedNote: "A#5",
		vexFlowNote: "a#/5",
		frequency: 932.33,
		isBlack: true,
		octave: 5,
	},
	{
		note: "B5",
		localizedNote: "B5",
		vexFlowNote: "b/5",
		frequency: 987.77,
		isBlack: false,
		octave: 5,
	},
	{
		note: "C6",
		localizedNote: "C6",
		vexFlowNote: "c/6",
		frequency: 1046.5,
		isBlack: false,
		octave: 6,
	},
	{
		note: "C#6",
		localizedNote: "C#6",
		vexFlowNote: "c#/6",
		frequency: 1108.73,
		isBlack: true,
		octave: 6,
	},
	{
		note: "D6",
		localizedNote: "D6",
		vexFlowNote: "d/6",
		frequency: 1174.66,
		isBlack: false,
		octave: 6,
	},
	{
		note: "D#6",
		localizedNote: "D#6",
		vexFlowNote: "d#/6",
		frequency: 1244.51,
		isBlack: true,
		octave: 6,
	},
	{
		note: "E6",
		localizedNote: "E6",
		vexFlowNote: "e/6",
		frequency: 1318.51,
		isBlack: false,
		octave: 6,
	},
	{
		note: "F6",
		localizedNote: "F6",
		vexFlowNote: "f/6",
		frequency: 1396.91,
		isBlack: false,
		octave: 6,
	},
	{
		note: "F#6",
		localizedNote: "F#6",
		vexFlowNote: "f#/6",
		frequency: 1479.98,
		isBlack: true,
		octave: 6,
	},
	{
		note: "G6",
		localizedNote: "G6",
		vexFlowNote: "g/6",
		frequency: 1567.98,
		isBlack: false,
		octave: 6,
	},
	{
		note: "G#6",
		localizedNote: "G#6",
		vexFlowNote: "g#/6",
		frequency: 1661.22,
		isBlack: true,
		octave: 6,
	},
	{
		note: "A6",
		localizedNote: "A6",
		vexFlowNote: "a/6",
		frequency: 1760.0,
		isBlack: false,
		octave: 6,
	},
	{
		note: "A#6",
		localizedNote: "A#6",
		vexFlowNote: "a#/6",
		frequency: 1864.66,
		isBlack: true,
		octave: 6,
	},
	{
		note: "B6",
		localizedNote: "B6",
		vexFlowNote: "b/6",
		frequency: 1975.53,
		isBlack: false,
		octave: 6,
	},
	{
		note: "C7",
		localizedNote: "C7",
		vexFlowNote: "c/7",
		frequency: 2093.0,
		isBlack: false,
		octave: 7,
	},
	{
		note: "C#7",
		localizedNote: "C#7",
		vexFlowNote: "c#/7",
		frequency: 2217.46,
		isBlack: true,
		octave: 7,
	},
	{
		note: "D7",
		localizedNote: "D7",
		vexFlowNote: "d/7",
		frequency: 2349.32,
		isBlack: false,
		octave: 7,
	},
	{
		note: "D#7",
		localizedNote: "D#7",
		vexFlowNote: "d#/7",
		frequency: 2489.02,
		isBlack: true,
		octave: 7,
	},
	{
		note: "E7",
		localizedNote: "E7",
		vexFlowNote: "e/7",
		frequency: 2637.02,
		isBlack: false,
		octave: 7,
	},
	{
		note: "F7",
		localizedNote: "F7",
		vexFlowNote: "f/7",
		frequency: 2793.83,
		isBlack: false,
		octave: 7,
	},
	{
		note: "F#7",
		localizedNote: "F#7",
		vexFlowNote: "f#/7",
		frequency: 2959.96,
		isBlack: true,
		octave: 7,
	},
	{
		note: "G7",
		localizedNote: "G7",
		vexFlowNote: "g/7",
		frequency: 3135.96,
		isBlack: false,
		octave: 7,
	},
	{
		note: "G#7",
		localizedNote: "G#7",
		vexFlowNote: "g#/7",
		frequency: 3322.44,
		isBlack: true,
		octave: 7,
	},
	{
		note: "A7",
		localizedNote: "A7",
		vexFlowNote: "a/7",
		frequency: 3520.0,
		isBlack: false,
		octave: 7,
	},
	{
		note: "A#7",
		localizedNote: "A#7",
		vexFlowNote: "a#/7",
		frequency: 3729.31,
		isBlack: true,
		octave: 7,
	},
	{
		note: "B7",
		localizedNote: "B7",
		vexFlowNote: "b/7",
		frequency: 3951.07,
		isBlack: false,
		octave: 7,
	},
	{
		note: "C8",
		localizedNote: "C8",
		vexFlowNote: "c/8",
		frequency: 4186.01,
		isBlack: false,
		octave: 8,
	},
];

export const noteTranslations: Record<string, Record<string, string>> = {
	en: { B: "B" }, // English uses B
	de: { B: "H" }, // German uses H
};
